  ## Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  ## Build
  - docker build -t reverseproxy ./reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  ## Tagging
  - docker tag reverseproxy byebyegomennasai/reverseproxy:v1
  - docker tag udagram-api-user byebyegomennasai/udagram-api-user:v1
  - docker tag udagram-api-feed byebyegomennasai/udagram-api-feed:v1
  - docker tag udagram-frontend byebyegomennasai/udagram-frontend:v1
  ## Push
  - docker push byebyegomennasai/reverseproxy:v1
  - docker push byebyegomennasai/udagram-api-user:v1
  - docker push byebyegomennasai/udagram-api-feed:v1
  - docker push byebyegomennasai/udagram-frontend:v1